'\" t
.\"     Title: xmppc
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 05/16/2020
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "XMPPC" "1" "05/16/2020" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
xmppc \- XMPP Command line Tool
.SH "SYNOPSIS"
.sp
\fIxmppc\fR [\fIOPTIONS\fR] \-m \fIMODE\fR \fICOMMAND\fR [<args>\&...]
.sp
\fIxmppc\fR [\-a \fIACCOUNT\fR] [\-j \fIJID\fR] [\-p \fIPASSWORD\fR] \-m \fIMODE\fR \fICOMMAND\fR [<args>\&...]
.SH "DESCRIPTION"
.sp
xmppc is a XMPP command line tool\&. You need an XMPP Account to use this tool\&. The account information can be defined via command line argument \-j \fIJID\fR\&. If no password is provided via \-p \fIPASSWORD\fR xmppc will ask the user to enter the password\&. Another option is to define 1 or more accounts within a configuration file\&. The option \-a \fIACCOUNT\fR can be used to select the account\&.
.sp
The argument \-m \fIMODE\fR defines the xmppc \fIMODE\fR which should be used (roster, message, pgp, omemo, openpgp, monitor, bookmark, mam, discovery)\&. The \fICOMMAND\fR and the args required by the \fICOMMAND\fR depends on the chosen \fIMODE\fR\&.
.SH "OPTIONS"
.PP
\fB\-a, \-\-attribute\fR \fIACCOUNT\fR
.RS 4
\fIACCOUNT\fR
is a name of a xmpp account defined within the configuration file\&.
.RE
.PP
\fB\-j, \-\-jid\fR \fIJID\fR
.RS 4
\fIJID\fR
of the XMPP Account\&.
.RE
.PP
\fB\-p, \-\-pwd\fR \fIPWD\fR
.RS 4
Password of the XMPP Account\&.
.RE
.PP
\fB\-v\fR \fIVERBOSE\fR, Verbose flags\&. \-v[v[v[v]]]
.RS 4
\-v is WARN \-vv is INFO \-\-vvv is DEBUG \-vvvv is TRACE
.RE
.PP
\fB\-\-help\fR
.RS 4
Print program version number and help
.RE
.SH "MODES AND COMMANDS"
.sp
xmppc modes\&.
.PP
\fB\-m roster\fR
.RS 4
The Roster mode can be used to provided information of the xmpp account\(cqs roster\&. The roster is the XMPP list of contacts\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBlist\fR
\- List all contacts
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBexport\fR
\- Exports all contacts
.RE
.RE
.PP
\fB\-m message\fR
.RS 4
The message mode can be used to send unencrypted messages to another xmpp account\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBchat <jid> <message>\fR
\- Sending unencrypted message to jid
.RE
.RE
.PP
\fB\-m pgp\fR
.RS 4
PGP Mode (XEP\-0027)
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBchat <jid> <message>\fR
\- Sending pgp encrypted message to jid
.RE
.RE
.PP
\fB\-m omemo\fR
.RS 4
OMEMO Mode (XEP\-0384)
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBlist\fR
\- List the device IDs and fingerprints
.RE
.RE
.PP
\fB\-m openpgp\fR
.RS 4
openpgp mode (XEP\-0373)
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBsigncrypt <jid> <message>\fR
\- Sending pgp signed and encrypted message to jid
.RE
.RE
.PP
\fB\-m monitor\fR
.RS 4
Monitot mode
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBstanza\fR
\- Stanza Monitor
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBmonitor\fR
\- microblog Monitor microblog (XEP\-0277)
.RE
.RE
.PP
\fB\-m bookmark\fR
.RS 4
Bookmark mode (XEP\-0048)
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBlist\fR
\- List bookmarks
.RE
.RE
.PP
\fB\-m mam\fR
.RS 4
Message Archive Management (XEP\-0313)
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBlist <jid>\fR
\- List messages from <jid>
.RE
.RE
.PP
\fB\-m discovery\fR
.RS 4
Service Discovery (XEP\-0030)
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBinfo <jid>\fR
\- info request for <jid>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBitem <jid>\fR
\- item request for <jid>
.RE
.RE
.SH "ENVIRONMENT VARIABLES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
HOME
.RE
.SH "EXAMPLES"
.sp
.if n \{\
.RS 4
.\}
.nf
xmppc \-\-jid user@domain\&.tld \-\-pwd "secret" \-\-mode roster list
xmppc \-\-jid user@domain\&.tld \-\-mode pgp chat friend@domain\&.tld "Hello"
xmppc \-a account1 \-\-mode discovery item conference@domain\&.tld
xmppc \-\-mode bookmark list
.fi
.if n \{\
.RE
.\}
.SH "FILES"
.sp
Configuration file to setup accounts\&.
.PP
\fB~/\&.config/xmppc\&.conf\fR
.RS 4
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
[default]
jid=account1@domain\&.tld
pwd=password1
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
[account2]
jid=account2@domain\&.tld
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
[account3]
jid=account3@domain\&.tld
pwd=password3
.fi
.if n \{\
.RE
.\}
.RE
.SH "EXIT STATUS"
.PP
\fB0\fR
.RS 4
Success
.RE
.PP
\fB1\fR
.RS 4
Failure
.RE
.SH "BUGS"
.sp
See https://codeberg\&.org/Anoxinon_e\&.V\&./xmppc/issues
.SH "AUTHOR"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
DebXWoody (OpenPGP: A602F76893F138B4A8EFDDD5C2DC916F35751C24)
.RE
.SH "RESOURCES"
.sp
Source: https://codeberg\&.org/Anoxinon_e\&.V\&./xmppc
.sp
Documentation: https://codeberg\&.org/Anoxinon_e\&.V\&./xmppc/wiki
.SH "COPYING"
.sp
Copyright (C) 2020 Anoxinon e\&.V\&. Free use of this software is granted under the terms of the GNU General Public License (GPL)\&.
